### ISSUE TITLE
Does development of this driver continuing?

### ISSUE THREAD

**Issue by nukdokplex** [indev29/egis0570#4]
I really interested in this driver and I hope this project is developing now. Is it?

**Comment by saeedark** [comment]
as press type sensor, development is complete but, matching algorithms used in fprint isn't designed for these small sensors. I don't have time right now but, I will develop it as a swipe type of sensor. :)

**Comment by indev29** [comment]
> I really interested in this driver and I hope this project is developing now. Is it?

Right now it's not possible to make the driver work due to the libfprint implementation, you can see my explanation [here](https://gitlab.freedesktop.org/libfprint/libfprint/-/issues/162#note_544560). I'll happily finish it as soon as the required changes are done in the library. 
At the same time, it's possible that the concept mentioned by @saeedark would work so it's up to him to implement it.

**Comment by nukdokplex** [comment]
Thank you all, guys! I never worked with drivers on linux so I think it's really hard.
